name: System file changes

on:
  push:

# No GITHUB_TOKEN permissions, as we don't use it.
permissions: {}

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Block if author/actor is not admin or BCD owner
        env:
          ACTOR: caugner
          AUTHOR: Elchi3
          GH_TOKEN: ${{ secrets.ORG_PAT }}
        run: |
          is_admin_or_owner() {
            local user="$1"
            echo "Checking user: $user"

            local perm
            perm=$(gh api "repos/mdn/browser-compat-data/collaborators/$user/permission" --jq .permission 2> /dev/null || true)

            if [ "$perm" = "admin" ]; then
              return 0
            fi

            local state
            state=$(gh api "orgs/mdn/teams/bcd-owners/memberships/$user" --jq .state 2> /dev/null || true)

            if [ "$state" = "active" ]; then
              return 0
            fi

            echo "User ($user) is not an admin, and not a BCD owner; please ping someone for a review."
            exit 1
          }

          # Check PR author.
          is_admin_or_owner "$AUTHOR"

          # Check actor.
          if [ "$ACTOR" != "$AUTHOR" ]; then
            is_admin_or_owner "$ACTOR"
          fi
